/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AppPPenIdRouteImport } from './routes/app/p/$penId'
import { Route as MarketingPSlugRouteImport } from './routes/_marketing/p/$slug'
import { Route as MarketingAuthRegisterRouteImport } from './routes/_marketing/auth/register'
import { Route as MarketingAuthLoginRouteImport } from './routes/_marketing/auth/login'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/_marketing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPPenIdRoute = AppPPenIdRouteImport.update({
  id: '/app/p/$penId',
  path: '/app/p/$penId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPSlugRoute = MarketingPSlugRouteImport.update({
  id: '/_marketing/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAuthRegisterRoute = MarketingAuthRegisterRouteImport.update({
  id: '/_marketing/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAuthLoginRoute = MarketingAuthLoginRouteImport.update({
  id: '/_marketing/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppIndexRoute
  '/auth/login': typeof MarketingAuthLoginRoute
  '/auth/register': typeof MarketingAuthRegisterRoute
  '/p/$slug': typeof MarketingPSlugRoute
  '/app/p/$penId': typeof AppPPenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/app': typeof AppIndexRoute
  '/auth/login': typeof MarketingAuthLoginRoute
  '/auth/register': typeof MarketingAuthRegisterRoute
  '/p/$slug': typeof MarketingPSlugRoute
  '/app/p/$penId': typeof AppPPenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing/': typeof MarketingIndexRoute
  '/app/': typeof AppIndexRoute
  '/_marketing/auth/login': typeof MarketingAuthLoginRoute
  '/_marketing/auth/register': typeof MarketingAuthRegisterRoute
  '/_marketing/p/$slug': typeof MarketingPSlugRoute
  '/app/p/$penId': typeof AppPPenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth/login'
    | '/auth/register'
    | '/p/$slug'
    | '/app/p/$penId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth/login'
    | '/auth/register'
    | '/p/$slug'
    | '/app/p/$penId'
  id:
    | '__root__'
    | '/_marketing/'
    | '/app/'
    | '/_marketing/auth/login'
    | '/_marketing/auth/register'
    | '/_marketing/p/$slug'
    | '/app/p/$penId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  MarketingAuthLoginRoute: typeof MarketingAuthLoginRoute
  MarketingAuthRegisterRoute: typeof MarketingAuthRegisterRoute
  MarketingPSlugRoute: typeof MarketingPSlugRoute
  AppPPenIdRoute: typeof AppPPenIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/p/$penId': {
      id: '/app/p/$penId'
      path: '/app/p/$penId'
      fullPath: '/app/p/$penId'
      preLoaderRoute: typeof AppPPenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/p/$slug': {
      id: '/_marketing/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof MarketingPSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/auth/register': {
      id: '/_marketing/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof MarketingAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/auth/login': {
      id: '/_marketing/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof MarketingAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
  AppIndexRoute: AppIndexRoute,
  MarketingAuthLoginRoute: MarketingAuthLoginRoute,
  MarketingAuthRegisterRoute: MarketingAuthRegisterRoute,
  MarketingPSlugRoute: MarketingPSlugRoute,
  AppPPenIdRoute: AppPPenIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
